### ISSUE TITLE
provide ED50 thermal threshold and MMM in input table to calculate difference for global comparision

### ISSUE THREAD

**Issue by reefgenomics** [greenjune-ship-it/coral-future#16]
### To make a research:
NOAA has a huge amount of data and software to retrieve data, we can explore.
There could be something interesting (https://coastwatch.noaa.gov/cwn/data-access-tools.html) and also we can email them if they have some public API to display it as a separate layer in our React application.

**Comment by greenjune-ship-it** [comment]
Implemented in PR #24
